/*
 * wangjian<wangjian@minigui.org>
 */

#ifndef __SIZE_800_1280_H
#define __SIZE_800_1280_H

#define SCREEN_W        800
#define SCREEN_H        1280	//chenlf

/*the size of soft key board window*/
#define SKB_WIN_W       800
#define SKB_WIN_H       580

#define SKB_CLOSE_L     LINE_SPACE1*10+KEY_WIDTH*9
//#define SKB_CLOSE_L    	(LINE_SPACE1*8+7.5*KEY_WIDTH+LINE_SPACE1+SPACE_SPACE+ROW2_SPACE)
#define SKB_CLOSE_T     ROW4_TY
#define SKB_CLOSE_R     LINE_SPACE1*10+KEY_WIDTH*10
#define SKB_CLOSE_B     ROW4_BY

#define SKB_VW_L        LINE_SPACE1*5+KEY_WIDTH*4
#define SKB_VW_T        4
#define SKB_VW_R        760
#define SKB_VW_B        30

#define SKB_VW_PU_L     LINE_SPACE1*5+KEY_WIDTH*4
#define SKB_VW_PU_T     6
#define SKB_VW_PU_R     LINE_SPACE1*5+KEY_WIDTH*4+33
#define SKB_VW_PU_B     25

#define SKB_VW_PD_L     727
#define SKB_VW_PD_T     6
#define SKB_VW_PD_R     727+33
#define SKB_VW_PD_B     25

#define SKB_SW_L        LINE_SPACE1
#define SKB_SW_T		6
#define SKB_SW_R        LINE_SPACE1*4+KEY_WIDTH*4-LINE_SPACE1*2
#define SKB_SW_B		25

#define SKB_KW_L        0  
#define SKB_KW_T        42 
#define SKB_KW_R        800
#define SKB_KW_B        580

/***** rectangle of the keys*****/
#define  LINE_SPACE1		10
#define  SPACE_SPACE		7
#define  LINE_SPACE2		17
#define  SOFT_HEAD		131
#define  KEY_WIDTH		64
#define  KEY_HEIGH		95
#define  ROW2_SPACE		5
#define  NUM_ROW3_KEY_WIDTH	103
#define  ROW1_TY                SOFT_HEAD+LINE_SPACE2  
#define  ROW1_BY                SOFT_HEAD+LINE_SPACE2+KEY_HEIGH   
#define  ROW2_TY                SOFT_HEAD+LINE_SPACE2*2+KEY_HEIGH
#define  ROW2_BY                SOFT_HEAD+LINE_SPACE2*2+KEY_HEIGH*2
#define  ROW3_TY                SOFT_HEAD+LINE_SPACE2*3+KEY_HEIGH*2
#define  ROW3_BY                SOFT_HEAD+LINE_SPACE2*3+KEY_HEIGH*3
#define  ROW4_TY                SOFT_HEAD+LINE_SPACE2*4+KEY_HEIGH*3
#define  ROW4_BY                SOFT_HEAD+LINE_SPACE2*4+KEY_HEIGH*4



//For en keyboard....
#define RECT_EN_KEY_1           { LINE_SPACE1,			ROW1_TY,	LINE_SPACE1+KEY_WIDTH,		ROW1_BY}
#define RECT_EN_KEY_2           { LINE_SPACE1*2+KEY_WIDTH,	ROW1_TY,	LINE_SPACE1*2+KEY_WIDTH*2,	ROW1_BY}
#define RECT_EN_KEY_3           { LINE_SPACE1*3+KEY_WIDTH*2,	ROW1_TY,	LINE_SPACE1*3+KEY_WIDTH*3,	ROW1_BY}
#define RECT_EN_KEY_4           { LINE_SPACE1*4+KEY_WIDTH*3,	ROW1_TY,	LINE_SPACE1*4+KEY_WIDTH*4,	ROW1_BY}
#define RECT_EN_KEY_5           { LINE_SPACE1*5+KEY_WIDTH*4,	ROW1_TY,        LINE_SPACE1*5+KEY_WIDTH*5,      ROW1_BY}
#define RECT_EN_KEY_6           { LINE_SPACE1*6+KEY_WIDTH*5,	ROW1_TY,        LINE_SPACE1*6+KEY_WIDTH*6,      ROW1_BY}
#define RECT_EN_KEY_7           { LINE_SPACE1*7+KEY_WIDTH*6,	ROW1_TY,        LINE_SPACE1*7+KEY_WIDTH*7,      ROW1_BY}
#define RECT_EN_KEY_8           { LINE_SPACE1*8+KEY_WIDTH*7,	ROW1_TY,        LINE_SPACE1*8+KEY_WIDTH*8,      ROW1_BY}
#define RECT_EN_KEY_9           { LINE_SPACE1*9+KEY_WIDTH*8,	ROW1_TY,        LINE_SPACE1*9+KEY_WIDTH*9,      ROW1_BY}
#define RECT_EN_KEY_10          { LINE_SPACE1*10+KEY_WIDTH*9,	ROW1_TY,        LINE_SPACE1*10+KEY_WIDTH*10,	ROW1_BY}

#define RECT_EN_KEY_11          { LINE_SPACE1*1+0.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*1+1.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_12          { LINE_SPACE1*2+1.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*2+2.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_13          { LINE_SPACE1*3+2.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*3+3.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_14          { LINE_SPACE1*4+3.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*4+4.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_15          { LINE_SPACE1*5+4.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*5+5.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_16          { LINE_SPACE1*6+5.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*6+6.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_17          { LINE_SPACE1*7+6.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*7+7.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_18          { LINE_SPACE1*8+7.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*8+8.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}
#define RECT_EN_KEY_19          { LINE_SPACE1*9+8.5*KEY_WIDTH+ROW2_SPACE,	ROW2_TY,	LINE_SPACE1*9+9.5*KEY_WIDTH+ROW2_SPACE,	ROW2_BY}

#define RECT_EN_KEY_20          { LINE_SPACE1*1,				ROW3_TY,	LINE_SPACE1*1+1.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_21          { LINE_SPACE1*2+1.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*2+2.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_22          { LINE_SPACE1*3+2.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*3+3.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_23          { LINE_SPACE1*4+3.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*4+4.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_24          { LINE_SPACE1*5+4.5*KEY_WIDTH+ROW2_SPACE,  	ROW3_TY,        LINE_SPACE1*5+5.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_25          { LINE_SPACE1*6+5.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*6+6.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_26          { LINE_SPACE1*7+6.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*7+7.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_27          { LINE_SPACE1*8+7.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*8+8.5*KEY_WIDTH+ROW2_SPACE,	ROW3_BY}
#define RECT_EN_KEY_28          { LINE_SPACE1*9+8.5*KEY_WIDTH+ROW2_SPACE,	ROW3_TY,        LINE_SPACE1*10+10*KEY_WIDTH,		ROW3_BY}

#define RECT_EN_KEY_29          { LINE_SPACE1*1,				ROW4_TY,	LINE_SPACE1*1+1.5*KEY_WIDTH+ROW2_SPACE,	ROW4_BY}
#define RECT_EN_KEY_30          { LINE_SPACE1*2+1.5*KEY_WIDTH+ROW2_SPACE,	ROW4_TY,	LINE_SPACE1*2+2.5*KEY_WIDTH-LINE_SPACE1-SPACE_SPACE+ROW2_SPACE,	ROW4_BY}
#define RECT_EN_KEY_31          { LINE_SPACE1*2+2.5*KEY_WIDTH-SPACE_SPACE+ROW2_SPACE,	ROW4_TY,LINE_SPACE1*7+7.5*KEY_WIDTH+LINE_SPACE1+SPACE_SPACE+ROW2_SPACE, ROW4_BY}
//#define RECT_EN_KEY_32          { LINE_SPACE1*8+7.5*KEY_WIDTH+LINE_SPACE1+SPACE_SPACE+ROW2_SPACE, ROW4_TY, LINE_SPACE1*10+KEY_WIDTH*10, ROW4_BY}
#define RECT_EN_KEY_32          { LINE_SPACE1*8+7.5*KEY_WIDTH+LINE_SPACE1+SPACE_SPACE+ROW2_SPACE, ROW4_TY,LINE_SPACE1*9+KEY_WIDTH*9,	ROW4_BY}
//#define RECT_EN_KEY_32          { LINE_SPACE1*10+KEY_WIDTH*9,			ROW4_TY,	LINE_SPACE1*10+KEY_WIDTH*10,		ROW4_BY}

//For num keyboard....
#define RECT_NUM_KEY_1          { LINE_SPACE1,			ROW1_TY,	LINE_SPACE1+KEY_WIDTH,		ROW1_BY}
#define RECT_NUM_KEY_2          { LINE_SPACE1*2+KEY_WIDTH,	ROW1_TY,	LINE_SPACE1*2+KEY_WIDTH*2,	ROW1_BY}
#define RECT_NUM_KEY_3          { LINE_SPACE1*3+KEY_WIDTH*2,	ROW1_TY,	LINE_SPACE1*3+KEY_WIDTH*3,	ROW1_BY}
#define RECT_NUM_KEY_4          { LINE_SPACE1*4+KEY_WIDTH*3,	ROW1_TY,	LINE_SPACE1*4+KEY_WIDTH*4,	ROW1_BY}
#define RECT_NUM_KEY_5          { LINE_SPACE1*5+KEY_WIDTH*4,	ROW1_TY,        LINE_SPACE1*5+KEY_WIDTH*5,      ROW1_BY}
#define RECT_NUM_KEY_6          { LINE_SPACE1*6+KEY_WIDTH*5,	ROW1_TY,        LINE_SPACE1*6+KEY_WIDTH*6,      ROW1_BY}
#define RECT_NUM_KEY_7          { LINE_SPACE1*7+KEY_WIDTH*6,	ROW1_TY,        LINE_SPACE1*7+KEY_WIDTH*7,      ROW1_BY}
#define RECT_NUM_KEY_8          { LINE_SPACE1*8+KEY_WIDTH*7,	ROW1_TY,        LINE_SPACE1*8+KEY_WIDTH*8,      ROW1_BY}
#define RECT_NUM_KEY_9          { LINE_SPACE1*9+KEY_WIDTH*8,	ROW1_TY,        LINE_SPACE1*9+KEY_WIDTH*9,      ROW1_BY}
#define RECT_NUM_KEY_10         { LINE_SPACE1*10+KEY_WIDTH*9,	ROW1_TY,        LINE_SPACE1*10+KEY_WIDTH*10,	ROW1_BY}

#define RECT_NUM_KEY_11         { LINE_SPACE1,			ROW2_TY,	LINE_SPACE1+KEY_WIDTH,		ROW2_BY}
#define RECT_NUM_KEY_12         { LINE_SPACE1*2+KEY_WIDTH,	ROW2_TY,	LINE_SPACE1*2+KEY_WIDTH*2,	ROW2_BY}
#define RECT_NUM_KEY_13         { LINE_SPACE1*3+KEY_WIDTH*2,	ROW2_TY,	LINE_SPACE1*3+KEY_WIDTH*3,	ROW2_BY}
#define RECT_NUM_KEY_14         { LINE_SPACE1*4+KEY_WIDTH*3,	ROW2_TY,	LINE_SPACE1*4+KEY_WIDTH*4,	ROW2_BY}
#define RECT_NUM_KEY_15         { LINE_SPACE1*5+KEY_WIDTH*4,	ROW2_TY,        LINE_SPACE1*5+KEY_WIDTH*5,      ROW2_BY}
#define RECT_NUM_KEY_16         { LINE_SPACE1*6+KEY_WIDTH*5,	ROW2_TY,        LINE_SPACE1*6+KEY_WIDTH*6,      ROW2_BY}
#define RECT_NUM_KEY_17         { LINE_SPACE1*7+KEY_WIDTH*6,	ROW2_TY,        LINE_SPACE1*7+KEY_WIDTH*7,      ROW2_BY}
#define RECT_NUM_KEY_18         { LINE_SPACE1*8+KEY_WIDTH*7,	ROW2_TY,        LINE_SPACE1*8+KEY_WIDTH*8,      ROW2_BY}
#define RECT_NUM_KEY_19         { LINE_SPACE1*9+KEY_WIDTH*8,	ROW2_TY,        LINE_SPACE1*9+KEY_WIDTH*9,      ROW2_BY}
#define RECT_NUM_KEY_20         { LINE_SPACE1*10+KEY_WIDTH*9,	ROW2_TY,        LINE_SPACE1*10+KEY_WIDTH*10,	ROW2_BY}

#define RECT_NUM_KEY_21         { LINE_SPACE1,				ROW3_TY,	LINE_SPACE1+NUM_ROW3_KEY_WIDTH,		ROW3_BY}
#define RECT_NUM_KEY_22         { LINE_SPACE1*2+NUM_ROW3_KEY_WIDTH,	ROW3_TY,	LINE_SPACE1*2+NUM_ROW3_KEY_WIDTH*2,	ROW3_BY}
#define RECT_NUM_KEY_23         { LINE_SPACE1*3+NUM_ROW3_KEY_WIDTH*2,	ROW3_TY,	LINE_SPACE1*3+NUM_ROW3_KEY_WIDTH*3,	ROW3_BY}
#define RECT_NUM_KEY_24         { LINE_SPACE1*4+NUM_ROW3_KEY_WIDTH*3,	ROW3_TY,	LINE_SPACE1*4+NUM_ROW3_KEY_WIDTH*4,	ROW3_BY}
#define RECT_NUM_KEY_25         { LINE_SPACE1*5+NUM_ROW3_KEY_WIDTH*4,	ROW3_TY,	LINE_SPACE1*5+NUM_ROW3_KEY_WIDTH*5,	ROW3_BY}
#define RECT_NUM_KEY_26         { LINE_SPACE1*6+NUM_ROW3_KEY_WIDTH*5,	ROW3_TY,	LINE_SPACE1*6+NUM_ROW3_KEY_WIDTH*6,	ROW3_BY}
#define RECT_NUM_KEY_27         { LINE_SPACE1*7+NUM_ROW3_KEY_WIDTH*6,	ROW3_TY,	LINE_SPACE1*7+NUM_ROW3_KEY_WIDTH*7,	ROW3_BY}

#define RECT_NUM_KEY_28         { LINE_SPACE1*1,				ROW4_TY,	LINE_SPACE1*1+1.5*KEY_WIDTH+ROW2_SPACE,	ROW4_BY}
#define RECT_NUM_KEY_29         { LINE_SPACE1*2+1.5*KEY_WIDTH+ROW2_SPACE,	ROW4_TY,	LINE_SPACE1*2+2.5*KEY_WIDTH-LINE_SPACE1-SPACE_SPACE+ROW2_SPACE,	ROW4_BY}
#define RECT_NUM_KEY_30         { LINE_SPACE1*2+2.5*KEY_WIDTH-SPACE_SPACE+ROW2_SPACE,	ROW4_TY,LINE_SPACE1*7+7.5*KEY_WIDTH+LINE_SPACE1+SPACE_SPACE+ROW2_SPACE, ROW4_BY}
#define RECT_NUM_KEY_31         { LINE_SPACE1*8+7.5*KEY_WIDTH+LINE_SPACE1+SPACE_SPACE+ROW2_SPACE, ROW4_TY,LINE_SPACE1*9+KEY_WIDTH*9,	ROW4_BY}
                                
#endif
