#!/bin/bash

# CMake Helper Script for Korean Input System
echo "CMake Helper for Korean Input System"
echo "===================================="
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$SCRIPT_DIR"
BUILD_DIR="$SOURCE_DIR/build"

echo "Source directory: $SOURCE_DIR"
echo "Build directory: $BUILD_DIR"
echo ""

echo "Common CMake Commands:"
echo "======================"
echo ""
echo "1. Configure and build from source directory:"
echo "   cd $SOURCE_DIR"
echo "   cmake -B build"
echo "   cmake --build build"
echo ""
echo "2. Configure and build from build directory:"
echo "   cd $BUILD_DIR"
echo "   cmake .."
echo "   make"
echo ""
echo "3. Clean build:"
echo "   cd $BUILD_DIR"
echo "   make clean"
echo "   cmake .."
echo "   make"
echo ""
echo "4. Clean everything:"
echo "   cd $BUILD_DIR"
echo "   make clean-all"
echo "   cmake .."
echo "   make"
echo ""
echo "5. Build specific targets:"
echo "   cd $BUILD_DIR"
echo "   make main                    # Build main application only"
echo "   make test_chunjiin          # Build ChunJiIn test only"
echo "   make calendar_test          # Build calendar test only"
echo ""
echo "6. Run the application:"
echo "   cd $BUILD_DIR"
echo "   ./main"
echo ""
echo "7. Run tests:"
echo "   cd $BUILD_DIR"
echo "   ./test_chunjiin"
echo "   ./test_chunjiin_simple"
echo "   ./calendar_test"
echo "   ./test_gwon_standalone"
echo ""
echo "Available build scripts:"
echo "======================="
echo "   ./build.sh                   # Full build using cmake"
echo "   ./build_test.sh              # Build and run tests"
echo "" 